name: Build & Deploy
run-name: Build & Deploy (${{ github.ref_name }})

on: push

concurrency: build-deploy-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16
          check-latest: true
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Setup utilities
        run: |
          sudo apt-get update
          sudo apt-get -y install zstd
      - name: Show versions of environment components (debug)
        run: |
          echo "Node.js: $(node -v)"
          echo "pnpm: $(pnpm -v)"
          echo "zstd: $(zstd -V)"
      - name: Install dependencies
        run: pnpm install
      - name: Build standalone server
        run: pnpm run build
      - name: Package the build
        run: |
          tar -cvf build.tar .output ecosystem.config.js
          zstd -11 -T0 build.tar
      - name: Upload the build
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ github.ref_name }}-${{ github.sha }}
          path: build.tar.zst

  deploy-prod:
    name: Deploy to production
    if: github.repository == 'ThrRip/mzg.fan' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-22.04
    env:
      PROD_CLOUD_SSH_URI: ${{ secrets.PROD_CLOUD_SSH_URI }}
      PROD_CLOUD_SSH_PORT: ${{ secrets.PROD_CLOUD_SSH_PORT }}
      PROD_CLOUD_SSH_KEY: ${{ secrets.PROD_CLOUD_SSH_KEY }}
      PROD_CLOUD_SSH_KEY_PATH: ${{ secrets.PROD_CLOUD_SSH_KEY_PATH }}
      PROD_CLOUD_PROJECT_ROOT: ${{ secrets.PROD_CLOUD_PROJECT_ROOT }}
    steps:
      - name: Setup utilities
        run: |
          sudo apt-get update
          sudo apt-get -y install rsync
      - name: Show versions of environment components (debug)
        run: |
          echo "rsync: $(rsync -V)"
      - name: Download the build
        uses: actions/download-artifact@v3
        with:
          name: build-${{ github.ref_name }}-${{ github.sha }}
      - name: Retrieve the SSH key
        run: echo -n "$PROD_CLOUD_SSH_KEY" > $PROD_CLOUD_SSH_KEY_PATH
      - name: Upload to the server
        run: |
          rsync -ahP \
            -e "ssh -i $PROD_CLOUD_SSH_KEY_PATH -p $PROD_CLOUD_SSH_PORT" \
            build.tar.zst \
            $PROD_CLOUD_SSH_URI:"$PROD_CLOUD_PROJECT_ROOT"
      - name: Replace the last build
        run: |
          ssh \
            -i $PROD_CLOUD_SSH_KEY_PATH \
            -p $PROD_CLOUD_SSH_PORT \
            $PROD_CLOUD_SSH_URI <<END
              shopt -s extglob
              cd "$PROD_CLOUD_PROJECT_ROOT"
              pm2 stop mzg.fan
              pm2 delete mzg.fan
              rm -fr !(build.tar.zst)
              zstd -d build.tar.zst
              tar -xvf build.tar
              rm -f build.tar.zst build.tar
              pm2 start ecosystem.config.js
              pm2 save
            END
