name: Build & Deploy / home
run-name: Build & Deploy (${{ github.ref_name }}/home)

on:
  push:
    paths:
      - 'packages/home/**'

jobs:
  build-deploy-home:
    name: Build & Deploy
    uses: ./.github/workflows/build-deploy.yml
    with:
      package: home
      package_cap: HOME
    secrets: inherit
