name: Build & Deploy / [all]
run-name: Build & Deploy (${{ github.ref_name }}/[all])

on:
  push:
    paths-ignore:
      - '.idea/**'
      - '.run/**'
      - 'database/**'
      - 'packages/**'
      - '.editorconfig'
      - '.eslintrc.js'

jobs:
  build-deploy:
    name: Build & Deploy / ${{ matrix.package }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: home
            package_cap: HOME
          - package: admin
            package_cap: ADMIN
    uses: ./.github/workflows/build-deploy.yml
    with:
      package: ${{ matrix.package }}
      package_cap: ${{ matrix.package_cap }}
    secrets: inherit
