name: Build & Deploy / admin
run-name: Build & Deploy (${{ github.ref_name }}/admin)

on:
  push:
    paths:
      - 'packages/admin/**'

jobs:
  build-deploy-admin:
    name: Build & Deploy
    uses: ./.github/workflows/build-deploy.yml
    with:
      package: admin
      package_cap: ADMIN
    secrets: inherit
