name: Check & Build & Deploy / home
run-name: Check & Build & Deploy (${{ github.ref_name }}/home)

on:
  push:
    paths:
      - '.github/**'
      - 'app/**'
      - 'packages/home/**'
      - 'Dockerfile'
      - 'nuxt.config.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'tailwind.config.ts'

jobs:
  check-build-deploy-home:
    name: Check & Build & Deploy
    uses: ./.github/workflows/check-build-deploy.yml
    with:
      package: home
      package_cap: HOME
    secrets: inherit
    permissions:
      packages: write
      attestations: write
      id-token: write
